### ISSUE TITLE
Error: HTTP error 500 (Internal Server Error) - Internal Error

### ISSUE THREAD

**Issue by creazy231** [bassarisse/google-spreadsheet-to-json#28]
I did't change anything but today I get a response with `Error: HTTP error 500 (Internal Server Error) - Internal Error` every time I try to open a sheet using `google-spreadsheet-to-json`.

Someone else got the same problem?

**Comment by elmercd** [comment]
Got the same error using the cli. This is the first time I got this issue. Me and my colleague have been using this package everyday for over a year now.

**Comment by creazy231** [comment]
Maybe a google related problem? 🤔

**Comment by creazy231** [comment]
In case it helps someone here is the full error:
```
Unhandled rejection Error: Error: HTTP error 500 (Internal Server Error) - Internal Error
    at maybeWrapAsError (C:\Users\creazy231\Documents\PROJEKTE\API\my-project\node_modules\google-spreadsheet-to-json\node_modules\bluebird\js\release\util.js:61:12)
    at C:\Users\creazy231\Documents\PROJEKTE\API\my-project\node_modules\google-spreadsheet-to-json\node_modules\bluebird\js\release\nodeback.js:38:50
    at C:\Users\creazy231\Documents\PROJEKTE\API\my-project\node_modules\google-spreadsheet\index.js:193:25
    at Request._callback (C:\Users\creazy231\Documents\PROJEKTE\API\my-project\node_modules\google-spreadsheet\index.js:153:20)
    at Request.self.callback (C:\Users\creazy231\Documents\PROJEKTE\API\my-project\node_modules\request\request.js:185:22)
    at Request.emit (events.js:193:13)
    at Request.<anonymous> (C:\Users\creazy231\Documents\PROJEKTE\API\my-project\node_modules\request\request.js:1161:10)
    at Request.emit (events.js:193:13)
    at Gunzip.<anonymous> (C:\Users\creazy231\Documents\PROJEKTE\API\my-project\node_modules\request\request.js:1083:12)
    at Object.onceWrapper (events.js:281:20)
    at Gunzip.emit (events.js:198:15)
    at endReadableNT (_stream_readable.js:1142:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
```

**Comment by elmercd** [comment]
I think this is google related problem.

https://support.google.com/docs/thread/5152040?hl=en&fbclid=IwAR0oG8O8IDsHiV3wmTJBXzFKwk_YI1nSibCTK-ubatdm2x0Aycl6qN4wcC0

**Comment by creazy231** [comment]
Thanks for the URL :)
Found an open issue in the google sheets repo https://github.com/theoephraim/node-google-spreadsheet/issues/231

**Comment by maxigimenez** [comment]
Same problem here

**Comment by theoephraim** [comment]
this appears to be a larger issue on google's side - https://issuetracker.google.com/issues/131613284

**Comment by elmercd** [comment]
I think google has resolved this one. Just tested this out and it works now.
